logging:
  level.root: info

spring:
  application:
    name: ts_user_service
  web:
    resources:
      add-mappings: false
  mongodb:
    uri: ${TS_USER_SERVICE_MONGODB_URI}
  data:
    mongodb:
      auto-index-creation: true


management:
  prometheus:
    metrics:
      export:
        properties:
          io:
            prometheus:
              exporter:
                exemplarsOnAllMetricTypes: false
  server:
    port: 10103
  endpoints:
    web:
      exposure:
        include: "health,prometheus,info,db,metrics"
    access:
      default: read_only
  endpoint:
    health:
      probes:
        enabled: true

mandatory:
  headers:
    routesToSkip:
      - "/actuator"
    startsWith:
      - "/actuator/"